### ISSUE TITLE
Parser not always re-running / removing errors when file is saved

### ISSUE THREAD

**Issue by boughtonp** [cfeclipse/cfeclipse#67] opened 2016-05-18 10:32 UTC
When saving a file after modifying a reported syntax error, it seems not to remove errors (only add new ones).

For example:

```
<cfscript>
    // reloading
;</cfscript>
```

Remove the semicolon there and the parser reports an error on save, but add it back in and it's necessary to close and open the file to remove the error, saving doesn't do it  - in fact, removing it again and saving adds the error to the tooltip each time.

Also, might be handy to having a re-parse option on the context menu (or using existing syntax highlighting option) that doesn't need saving the file.

**Comment by denuno** [comment] 2016-05-18 19:01
Hrm, I'm not seeing this locally... one thing to try, is to do the "Project > Clean.." bit, and see if that clears things up-- though since you can get them to go away and then have them come back, it's probably something else.

**Comment by denuno** [comment] 2016-12-26 23:22
I'm going to go ahead and close this, since the parsing has been changed a good bit since then and I can't reproduce this, but feel free to reopen if it is still happening or happens again.

**Closed by denuno** 2016-12-26 23:22 UTC
